name: .NET Desktop Build

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"

      - name: Restore
        run: dotnet restore "Timer/Timer/Timer.csproj"

      - name: Build
        run: dotnet build "Timer/Timer/Timer.csproj" -c Release --no-restore

